// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXND0b6WX5kmyxVg1wBoY5AOJp5-gIZSY',
    appId: '1:693720663766:web:c83e26e901cb3e898b6b77',
    messagingSenderId: '693720663766',
    projectId: 'personal-outfit-recommendation',
    authDomain: 'personal-outfit-recommendation.firebaseapp.com',
    storageBucket: 'personal-outfit-recommendation.firebasestorage.app',
    measurementId: 'G-WWD1EH8BZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3FwbJadCzoPYwU5OYsmPbmbACqCbjTwk',
    appId: '1:693720663766:android:be8f67009d3952c78b6b77',
    messagingSenderId: '693720663766',
    projectId: 'personal-outfit-recommendation',
    storageBucket: 'personal-outfit-recommendation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqPKfvDI8NIA_hyzn-0-I9f2nzSRbWrQY',
    appId: '1:693720663766:ios:c6d624be3fc15bff8b6b77',
    messagingSenderId: '693720663766',
    projectId: 'personal-outfit-recommendation',
    storageBucket: 'personal-outfit-recommendation.firebasestorage.app',
    iosBundleId: 'com.example.personalOutfitRecommendation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqPKfvDI8NIA_hyzn-0-I9f2nzSRbWrQY',
    appId: '1:693720663766:ios:c6d624be3fc15bff8b6b77',
    messagingSenderId: '693720663766',
    projectId: 'personal-outfit-recommendation',
    storageBucket: 'personal-outfit-recommendation.firebasestorage.app',
    iosBundleId: 'com.example.personalOutfitRecommendation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXND0b6WX5kmyxVg1wBoY5AOJp5-gIZSY',
    appId: '1:693720663766:web:4cdf40d25e7466288b6b77',
    messagingSenderId: '693720663766',
    projectId: 'personal-outfit-recommendation',
    authDomain: 'personal-outfit-recommendation.firebaseapp.com',
    storageBucket: 'personal-outfit-recommendation.firebasestorage.app',
    measurementId: 'G-4H5XJQB413',
  );

}